### ISSUE TITLE
Update the UI 

### ISSUE THREAD

**Issue by VinitGurjar** [adhiramaa/Javascript-Snake-Game#1]
The game I created don't contain any **text content** or **photos** and **score board**, If you can add this things then please create a better Interface.

**Comment by skippyr** [comment]
Hello, @adhiramaa. Your project is awesome! I want to try help you solve this issue.

I have forked your repository and create the `dev` branch with a simple implementation of a title and a score board that updates whenever the `expandSnake` is called, showing the current size of the snake. This update is make by the new function `updateScore` in the `snake.js`.

I also separated the styles to its own file, `style.css` and moved the `script` tag to the top of the `index.html` so the `defer` attribute can work.

I added a container to the `index.html` so I could add the title and the scoreboard, I still need to make it fully responsive just like the board.

I want to know what do you think that can be added as "text content" or "photos", is it like a preview photo in the `README`?

**Comment by VinitGurjar** [comment]
Awesome work @skippyr Thanks for your contribution

**Comment by VinitGurjar** [comment]
Also sorry I checked your contribution today

**Comment by VinitGurjar** [comment]
Text content or photos you can add this as you want

**Comment by skippyr** [comment]
Thank you for explaining, @adhiramaa! I will take a look again in your project and come back with a pull request later.
